
### Find a user with a given ID
GET http://localhost:3000/auth/4

### Find all users with a given Email
GET http://localhost:3000/auth?email=alexander@hotmail.com

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Get the currently signed in user
POST  http://localhost:3000/auth/signout

### Delete a User with a given id
DELETE  http://localhost:3000/auth/1234

### Sign in as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "alexander_@hotmail.com",
    "password": "asdfasdf@"
}

### Find a user with a given ID
PUT http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "alexander@hotmail.com",
    "password": "asdfasdf@"
}

### Update a user with a given ID
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "alexander@hotmail.com",
    "password": "2"
}